### PR TITLE
Update to ndarray 0.16

### LINKED ISSUE #96: Bumping `approx` dependency
For packaging to Fedora, it would be good if the dependency of `approx` can be bumped for the next release.

This would be in line with https://github.com/rust-ndarray/ndarray/pull/1380 when a release is tagged over there.

### LINKED ISSUE #97: Support master branch of `ndarray`
I want to use both methods in `ndarray`'s master branch and this crate. But this crate only supports specific `ndarray` (0.15.0 for now), which is incompatible with the master branch of `ndarray`.

I wonder if there is a way to use `ndarray-stats` and `ndarray`'s master branch instead of cloning and changing the dependencies to git URLs.

Maybe merging `ndarray-stats` to `ndarray` and forming a workspace is a solution. In such a way, [multiple locations](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations) could be used.

### PR DESCRIPTION
**Pull request by bluss**
Upgrade to ndarray 0.16, (approx 0.5, ndarray-rand 0.15)

Update MSRV to 1.64, like ndarray.

Update cross builders in CI as needed to pass.

Closes #97
Closes #96

### CODE REVIEW

**Comment by bluss** [comment]
All good now except that coverage doesn't pass (due to external service)

**Comment by bluss** [comment]
@xd009642 @jturner314 @LukeMathWalker I'll try to help here and go on to make a release

**Comment by altunenes** [comment]
thank you!

**Comment by LukeMathWalker** [comment]
Please do! I don't have bandwidth for the numerical ecosystem these days, but that shouldn't be a blocker here.

**Pull request merged**
