### PR TITLE
Improved Documentation

### PR DESCRIPTION
**Pull request by lebensterben**
histogram/grid.rs: Docs
- Added some doc tests
- Minor reformatting

### CODE REVIEW

**Comment by xd009642** [comment]
@lebensterben I was going to take a look at this with a view of merging it. Just wondering if there was a specific reason it was in draft i.e. more planned changes etc?

**Comment by xd009642** [comment]
So I've spent some time going over all these changes and I think they're all good and see no issues. So I'm going to merge this with the view of getting a new version of ndarray-stats out with them included :+1:

**Review by xd009642 — APPROVED** [review]

**Comment by lebensterben** [comment]
@xd009642 
Hi,
I spotted some features not implemented and started implementing them, but then I have to work on other stuff so it's not finished yet.

**Comment by xd009642** [comment]
Ah fair enough, if you want to raise an issue or open another PR since I merged this one. I think a general issue with a checklist of missing or lacking parts of the docs would be good

**Pull request merged**
