### PR TITLE
Bump version and dependencies post ndarray 0.14

### LINKED ISSUE #69: Release a new version to coincide with ndarray 0.14
Title is self-explanatory. I guess this is also a breaking change so should come with a minor version bump. It would also be good if the 2 PRs that are currently open could be sorted out :eyes:

### PR DESCRIPTION
**Pull request by xd009642**
For a quick release to coincide with ndarray 0.14. Also bumped all other deps since they required no code changes

Fixes #69

### CODE REVIEW

**Comment by LukeMathWalker** [comment]
Looks good to me :ok_hand: 
As evident, I don't have much time lately to dedicate to ndarray-related projects. I transferred ownership of `ndarray-stats` to the `release` team in the `rust-ndarray` org - I think you are best placed when it comes to choosing who should be part of it @bluss.
I am happy to cut this release though if necessary.

**Comment by bluss** [comment]
Travis needs update to build with 1.42 as min version.

I don't have much time for Rust either, unfortunately :( So we are looking for maintainers here

**Comment by xd009642** [comment]
Done, I also simplified the tarpaulin install as the rust flag isn't needed anymore now proc macro is stabilised :smile:

**Comment by bluss** [comment]
@LukeMathWalker  What do you think, we can welcome @xd009642 to be maintainer of ndarray-stats and ndarray?

**Comment by LukeMathWalker** [comment]
He has been around for a long time, he knows and uses both projects professionally, I know where he lives if he pulls anything funny - I think we can welcome him :grin:

**Comment by xd009642** [comment]
aha I have power now :upside_down_face:. Does anyone have any issues if I take a look at #63 and merging it before we push out a new release? I was having a read and it all looks pretty good to me, not sure why it's in draft

**Comment by bluss** [comment]
Also, join #rust-sci:matrix.org on matrix if you want to. It is not a lively place, but it's the place we have I think

**Comment by xd009642** [comment]
I'm going to merge this as I can now :wink:

**Pull request merged**
